name       : transmission-remote-gtk
version    : 1.3.1
release    : 2
source     :
    - https://github.com/transmission-remote-gtk/transmission-remote-gtk/releases/download/1.3.1/transmission-remote-gtk-1.3.1.tar.xz : 1b29c573b1e205e3e7c2433dc4a48f9574278d97e033845d19bbffa1d7f75345
license    : GPL-2.0
component  : network.download
summary    : transmission-remote-gtk is a GTK client for remote management of the
    Transmission BitTorrent client, using its HTTP RPC protocol
description: |
    transmission-remote-gtk is a GTK client for remote management of the Transmission BitTorrent client, using its HTTP RPC protocol
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - intltool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
