name       : transmission-remote-gtk
version    : 1.4.1
release    : 4
source     :
    - https://github.com/transmission-remote-gtk/transmission-remote-gtk/releases/download/1.4.1/transmission-remote-gtk-1.4.1.tar.xz : 59978381a558fc6d1a11091c702a88ac0be8fc7fa135ca367eec55f572a112ab
license    : GPL-2.0-or-later
component  : network.download
summary    : transmission-remote-gtk is a GTK client for remote management of the Transmission BitTorrent client, using its HTTP RPC protocol
description: |
    transmission-remote-gtk is a GTK client for remote management of the Transmission BitTorrent client, using its HTTP RPC protocol
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - intltool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
